dir: "{{.InterfaceDir}}/genmock"
structname: "{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}genmock"
filename: "{{.InterfaceName | snakecase}}.go"
template: testify
packages:
  github.com/llanuzo/card-game/internal/service:
    config:
      all: true
      pkgname: "svcgenmock"
