dir: '{{.InterfaceDir}}/genmock'
structname: '{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}genmock'
filename: '{{.InterfaceName | snakecase}}.go'
template: testify
# # Packages is required: mockery will fail if there's not atleast 1 specified
# packages:
#   github.com/llanuzo/exampleapp/internal/service:
#     config:
#       all: true
