// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package svcgenmock

import (
	"github.com/google/uuid"
	"github.com/llanuzo/card-game/internal/service/svcmodel"
	mock "github.com/stretchr/testify/mock"
)

// NewGame creates a new instance of Game. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGame(t interface {
	mock.TestingT
	Cleanup(func())
}) *Game {
	mock := &Game{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Game is an autogenerated mock type for the Game type
type Game struct {
	mock.Mock
}

type Game_Expecter struct {
	mock *mock.Mock
}

func (_m *Game) EXPECT() *Game_Expecter {
	return &Game_Expecter{mock: &_m.Mock}
}

// AddDeck provides a mock function for the type Game
func (_mock *Game) AddDeck(gameId uuid.UUID) error {
	ret := _mock.Called(gameId)

	if len(ret) == 0 {
		panic("no return value specified for AddDeck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(gameId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Game_AddDeck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDeck'
type Game_AddDeck_Call struct {
	*mock.Call
}

// AddDeck is a helper method to define mock.On call
//   - gameId uuid.UUID
func (_e *Game_Expecter) AddDeck(gameId interface{}) *Game_AddDeck_Call {
	return &Game_AddDeck_Call{Call: _e.mock.On("AddDeck", gameId)}
}

func (_c *Game_AddDeck_Call) Run(run func(gameId uuid.UUID)) *Game_AddDeck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Game_AddDeck_Call) Return(err error) *Game_AddDeck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Game_AddDeck_Call) RunAndReturn(run func(gameId uuid.UUID) error) *Game_AddDeck_Call {
	_c.Call.Return(run)
	return _c
}

// AddPlayer provides a mock function for the type Game
func (_mock *Game) AddPlayer(gameId uuid.UUID) (*svcmodel.Player, error) {
	ret := _mock.Called(gameId)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayer")
	}

	var r0 *svcmodel.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*svcmodel.Player, error)); ok {
		return returnFunc(gameId)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *svcmodel.Player); ok {
		r0 = returnFunc(gameId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*svcmodel.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(gameId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Game_AddPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlayer'
type Game_AddPlayer_Call struct {
	*mock.Call
}

// AddPlayer is a helper method to define mock.On call
//   - gameId uuid.UUID
func (_e *Game_Expecter) AddPlayer(gameId interface{}) *Game_AddPlayer_Call {
	return &Game_AddPlayer_Call{Call: _e.mock.On("AddPlayer", gameId)}
}

func (_c *Game_AddPlayer_Call) Run(run func(gameId uuid.UUID)) *Game_AddPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Game_AddPlayer_Call) Return(player *svcmodel.Player, err error) *Game_AddPlayer_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *Game_AddPlayer_Call) RunAndReturn(run func(gameId uuid.UUID) (*svcmodel.Player, error)) *Game_AddPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// AddPlayerCard provides a mock function for the type Game
func (_mock *Game) AddPlayerCard(gameId uuid.UUID, playerId uuid.UUID) error {
	ret := _mock.Called(gameId, playerId)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayerCard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(gameId, playerId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Game_AddPlayerCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlayerCard'
type Game_AddPlayerCard_Call struct {
	*mock.Call
}

// AddPlayerCard is a helper method to define mock.On call
//   - gameId uuid.UUID
//   - playerId uuid.UUID
func (_e *Game_Expecter) AddPlayerCard(gameId interface{}, playerId interface{}) *Game_AddPlayerCard_Call {
	return &Game_AddPlayerCard_Call{Call: _e.mock.On("AddPlayerCard", gameId, playerId)}
}

func (_c *Game_AddPlayerCard_Call) Run(run func(gameId uuid.UUID, playerId uuid.UUID)) *Game_AddPlayerCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Game_AddPlayerCard_Call) Return(err error) *Game_AddPlayerCard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Game_AddPlayerCard_Call) RunAndReturn(run func(gameId uuid.UUID, playerId uuid.UUID) error) *Game_AddPlayerCard_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type Game
func (_mock *Game) Create() *svcmodel.Game {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *svcmodel.Game
	if returnFunc, ok := ret.Get(0).(func() *svcmodel.Game); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*svcmodel.Game)
		}
	}
	return r0
}

// Game_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Game_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
func (_e *Game_Expecter) Create() *Game_Create_Call {
	return &Game_Create_Call{Call: _e.mock.On("Create")}
}

func (_c *Game_Create_Call) Run(run func()) *Game_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Game_Create_Call) Return(game *svcmodel.Game) *Game_Create_Call {
	_c.Call.Return(game)
	return _c
}

func (_c *Game_Create_Call) RunAndReturn(run func() *svcmodel.Game) *Game_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Game
func (_mock *Game) Delete(gameId uuid.UUID) error {
	ret := _mock.Called(gameId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(gameId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Game_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Game_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - gameId uuid.UUID
func (_e *Game_Expecter) Delete(gameId interface{}) *Game_Delete_Call {
	return &Game_Delete_Call{Call: _e.mock.On("Delete", gameId)}
}

func (_c *Game_Delete_Call) Run(run func(gameId uuid.UUID)) *Game_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Game_Delete_Call) Return(err error) *Game_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Game_Delete_Call) RunAndReturn(run func(gameId uuid.UUID) error) *Game_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlayer provides a mock function for the type Game
func (_mock *Game) DeletePlayer(gameId uuid.UUID, playerId uuid.UUID) error {
	ret := _mock.Called(gameId, playerId)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlayer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(gameId, playerId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Game_DeletePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlayer'
type Game_DeletePlayer_Call struct {
	*mock.Call
}

// DeletePlayer is a helper method to define mock.On call
//   - gameId uuid.UUID
//   - playerId uuid.UUID
func (_e *Game_Expecter) DeletePlayer(gameId interface{}, playerId interface{}) *Game_DeletePlayer_Call {
	return &Game_DeletePlayer_Call{Call: _e.mock.On("DeletePlayer", gameId, playerId)}
}

func (_c *Game_DeletePlayer_Call) Run(run func(gameId uuid.UUID, playerId uuid.UUID)) *Game_DeletePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Game_DeletePlayer_Call) Return(err error) *Game_DeletePlayer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Game_DeletePlayer_Call) RunAndReturn(run func(gameId uuid.UUID, playerId uuid.UUID) error) *Game_DeletePlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetCardsBySuit provides a mock function for the type Game
func (_mock *Game) GetCardsBySuit(gameId uuid.UUID) (map[svcmodel.CardSuit]int, error) {
	ret := _mock.Called(gameId)

	if len(ret) == 0 {
		panic("no return value specified for GetCardsBySuit")
	}

	var r0 map[svcmodel.CardSuit]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (map[svcmodel.CardSuit]int, error)); ok {
		return returnFunc(gameId)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) map[svcmodel.CardSuit]int); ok {
		r0 = returnFunc(gameId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[svcmodel.CardSuit]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(gameId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Game_GetCardsBySuit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardsBySuit'
type Game_GetCardsBySuit_Call struct {
	*mock.Call
}

// GetCardsBySuit is a helper method to define mock.On call
//   - gameId uuid.UUID
func (_e *Game_Expecter) GetCardsBySuit(gameId interface{}) *Game_GetCardsBySuit_Call {
	return &Game_GetCardsBySuit_Call{Call: _e.mock.On("GetCardsBySuit", gameId)}
}

func (_c *Game_GetCardsBySuit_Call) Run(run func(gameId uuid.UUID)) *Game_GetCardsBySuit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Game_GetCardsBySuit_Call) Return(cardSuitToInt map[svcmodel.CardSuit]int, err error) *Game_GetCardsBySuit_Call {
	_c.Call.Return(cardSuitToInt, err)
	return _c
}

func (_c *Game_GetCardsBySuit_Call) RunAndReturn(run func(gameId uuid.UUID) (map[svcmodel.CardSuit]int, error)) *Game_GetCardsBySuit_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Game
func (_mock *Game) List() []*svcmodel.Game {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*svcmodel.Game
	if returnFunc, ok := ret.Get(0).(func() []*svcmodel.Game); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*svcmodel.Game)
		}
	}
	return r0
}

// Game_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Game_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *Game_Expecter) List() *Game_List_Call {
	return &Game_List_Call{Call: _e.mock.On("List")}
}

func (_c *Game_List_Call) Run(run func()) *Game_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Game_List_Call) Return(games []*svcmodel.Game) *Game_List_Call {
	_c.Call.Return(games)
	return _c
}

func (_c *Game_List_Call) RunAndReturn(run func() []*svcmodel.Game) *Game_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListCardCounts provides a mock function for the type Game
func (_mock *Game) ListCardCounts(gameId uuid.UUID) ([]svcmodel.CardCount, error) {
	ret := _mock.Called(gameId)

	if len(ret) == 0 {
		panic("no return value specified for ListCardCounts")
	}

	var r0 []svcmodel.CardCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]svcmodel.CardCount, error)); ok {
		return returnFunc(gameId)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []svcmodel.CardCount); ok {
		r0 = returnFunc(gameId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]svcmodel.CardCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(gameId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Game_ListCardCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCardCounts'
type Game_ListCardCounts_Call struct {
	*mock.Call
}

// ListCardCounts is a helper method to define mock.On call
//   - gameId uuid.UUID
func (_e *Game_Expecter) ListCardCounts(gameId interface{}) *Game_ListCardCounts_Call {
	return &Game_ListCardCounts_Call{Call: _e.mock.On("ListCardCounts", gameId)}
}

func (_c *Game_ListCardCounts_Call) Run(run func(gameId uuid.UUID)) *Game_ListCardCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Game_ListCardCounts_Call) Return(cardCounts []svcmodel.CardCount, err error) *Game_ListCardCounts_Call {
	_c.Call.Return(cardCounts, err)
	return _c
}

func (_c *Game_ListCardCounts_Call) RunAndReturn(run func(gameId uuid.UUID) ([]svcmodel.CardCount, error)) *Game_ListCardCounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlayers provides a mock function for the type Game
func (_mock *Game) ListPlayers(gameId uuid.UUID) ([]*svcmodel.Player, error) {
	ret := _mock.Called(gameId)

	if len(ret) == 0 {
		panic("no return value specified for ListPlayers")
	}

	var r0 []*svcmodel.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]*svcmodel.Player, error)); ok {
		return returnFunc(gameId)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []*svcmodel.Player); ok {
		r0 = returnFunc(gameId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*svcmodel.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(gameId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Game_ListPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlayers'
type Game_ListPlayers_Call struct {
	*mock.Call
}

// ListPlayers is a helper method to define mock.On call
//   - gameId uuid.UUID
func (_e *Game_Expecter) ListPlayers(gameId interface{}) *Game_ListPlayers_Call {
	return &Game_ListPlayers_Call{Call: _e.mock.On("ListPlayers", gameId)}
}

func (_c *Game_ListPlayers_Call) Run(run func(gameId uuid.UUID)) *Game_ListPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Game_ListPlayers_Call) Return(players []*svcmodel.Player, err error) *Game_ListPlayers_Call {
	_c.Call.Return(players, err)
	return _c
}

func (_c *Game_ListPlayers_Call) RunAndReturn(run func(gameId uuid.UUID) ([]*svcmodel.Player, error)) *Game_ListPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlayersCards provides a mock function for the type Game
func (_mock *Game) ListPlayersCards(gameId uuid.UUID, playerId uuid.UUID) ([]svcmodel.Card, error) {
	ret := _mock.Called(gameId, playerId)

	if len(ret) == 0 {
		panic("no return value specified for ListPlayersCards")
	}

	var r0 []svcmodel.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) ([]svcmodel.Card, error)); ok {
		return returnFunc(gameId, playerId)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) []svcmodel.Card); ok {
		r0 = returnFunc(gameId, playerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]svcmodel.Card)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(gameId, playerId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Game_ListPlayersCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlayersCards'
type Game_ListPlayersCards_Call struct {
	*mock.Call
}

// ListPlayersCards is a helper method to define mock.On call
//   - gameId uuid.UUID
//   - playerId uuid.UUID
func (_e *Game_Expecter) ListPlayersCards(gameId interface{}, playerId interface{}) *Game_ListPlayersCards_Call {
	return &Game_ListPlayersCards_Call{Call: _e.mock.On("ListPlayersCards", gameId, playerId)}
}

func (_c *Game_ListPlayersCards_Call) Run(run func(gameId uuid.UUID, playerId uuid.UUID)) *Game_ListPlayersCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Game_ListPlayersCards_Call) Return(cards []svcmodel.Card, err error) *Game_ListPlayersCards_Call {
	_c.Call.Return(cards, err)
	return _c
}

func (_c *Game_ListPlayersCards_Call) RunAndReturn(run func(gameId uuid.UUID, playerId uuid.UUID) ([]svcmodel.Card, error)) *Game_ListPlayersCards_Call {
	_c.Call.Return(run)
	return _c
}

// Shuffle provides a mock function for the type Game
func (_mock *Game) Shuffle(gameId uuid.UUID) error {
	ret := _mock.Called(gameId)

	if len(ret) == 0 {
		panic("no return value specified for Shuffle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(gameId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Game_Shuffle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shuffle'
type Game_Shuffle_Call struct {
	*mock.Call
}

// Shuffle is a helper method to define mock.On call
//   - gameId uuid.UUID
func (_e *Game_Expecter) Shuffle(gameId interface{}) *Game_Shuffle_Call {
	return &Game_Shuffle_Call{Call: _e.mock.On("Shuffle", gameId)}
}

func (_c *Game_Shuffle_Call) Run(run func(gameId uuid.UUID)) *Game_Shuffle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Game_Shuffle_Call) Return(err error) *Game_Shuffle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Game_Shuffle_Call) RunAndReturn(run func(gameId uuid.UUID) error) *Game_Shuffle_Call {
	_c.Call.Return(run)
	return _c
}
